app:
  name: 'phylax'
  log_level: 'info'
  log_file: 'log/phylax/backup.log'

databases:
  - name: 'production-mysql'
    type: 'mysql'
    host: 'localhost'
    port: 3306
    username: 'root'
    password: ''
    database: 'sapabipa'
    enabled: true
    schedule: '0 */3 * * * *' # Every minute
    # schedule: '* * * * * *' # Every seconds

backup:
  retention_days: 14
  compress: true

  upload_targets:
    - type: 'local'
      enabled: true
      path: 'backups/databases'

    - type: 'gdrive'
      enabled: true
      credentials_file: 'client_secret.json'
      refresh_token: ''
      folder_id: ''
