app:
  name: 'phylax'
  log_level: 'info'
  log_file: 'log/phylax/backup.log'

databases:
  - name: 'production-mysql'
    type: 'mysql'
    host: 'localhost'
    port: 3306
    username: 'root'
    password: ''
    database: 'sapabipa'
    enabled: true
    schedule: '0 */3 * * * *' # Every minute

backup:
  local_path: 'backups/databases'
  retention_days: 14
  compress: true

  upload_targets:
    - type: 'local'
      enabled: true

    - type: 'gdrive'
      enabled: false
      credentials_file: '/etc/phylax/gdrive-credentials.json'
      folder_id: 'your_folder_id'
